# Generated by Django 3.2.14 on 2022-09-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('auther', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('article', models.FileField(upload_to='generalnotes')),
            ],
        ),
    ]
