# Generated by Django 3.2.14 on 2022-09-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='HomeImages',
        ),
    ]
