# Generated by Django 3.2.14 on 2022-09-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_images_homeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='home'),
        ),
        migrations.AddField(
            model_name='home',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='home'),
        ),
        migrations.AddField(
            model_name='home',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='home'),
        ),
        migrations.AddField(
            model_name='home',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='home'),
        ),
        migrations.DeleteModel(
            name='HomeImages',
        ),
    ]
