# Generated by Django 3.2.14 on 2022-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField()),
                ('title2', models.TextField()),
                ('image', models.ImageField(upload_to='about')),
                ('resume', models.FileField(upload_to='about')),
            ],
        ),
    ]
